[package]
name = "portfolio"
version = "0.1.0"
authors = ["j-arens <arens.joshua@sbcglobal.net>"]
edition = "2018"

[[bin]]
name = "mdparser"
path = "dev/md/parser.rs"

[dependencies]
pulldown-cmark = "0.6.0"
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"