name: cd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install js deps
        run: yarn
      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: parse posts
        run: cargo run
      - name: build js assets
        env:
          CONTACT_SUBMISSION_URL: 'http://stele.tech/contact'
          CONTACT_EMAIL: ${{ secrets.contact_email }}
          SENDGRID_KEY: ${{ secrets.sendgrid_key }}
          SENDGRID_ENDPOINT: 'https://api.sendgrid.com/v3/mail/send'
          STORAGE_URL: 'https://storage.googleapis.com/portfolio_assets'
        run: yarn build
      - name: push assets to cloud storage
        env:
          GC_EMAIL: ${{ secrets.gc_email }}
          GC_PKEY: ${{ secrets.gc_pkey_b64 }}
          GC_PROJECT_ID: ${{ secrets.gc_project_id }}
          GC_BUCKET_NAME: ${{ secrets.gc_bucket_name }}
        run: node dev/storage.js
      - name: push cloudflare worker bundle
        env:
          CF_EMAIL: ${{ secrets.cf_email }}
          CF_ACCOUNT_ID: ${{ secrets.cd_account_id }}
          CF_ZONE_ID: ${{ secrets.cf_zone_id }}
          CF_KEY: ${{ secrets.cf_key }}
        run: node dev/deploy-worker.js
